pipeline {
    agent any
    parameters {
        string(name: 'SSH_USER', defaultValue: 'sos', description: 'SSH username')
        string(name: 'SSH_PASSWORD', defaultValue: 'qwe123', description: 'SSH password')
    }
    stages {
        // 1. 从GitHub拉取代码
        stage('Checkout') {
            steps {
                git url: 'https://github.com/lwyx2000/koodo-reader.git',  
                     branch: 'dev',  // 修改分支为 dev
                     credentialsId: '8695ee47-da56-48c6-845e-0631ba4db951'  
            }
        }

        // 2. 编译项目
        stage('Build') {
            steps {
                script {
                    def nodeHome = tool 'nodejs'
                    env.PATH = "${nodeHome}/bin:${env.PATH}"
                    sh 'echo $PATH'
                    sh 'node -v'
                    sh 'npm -v'
                }
                sh 'npm config set registry https://registry.npmmirror.com'
                sh 'npm install --legacy-peer-deps'
                sh 'npm run build'
            }
        }

        // 3. 部署静态文件
        stage('Deploy to Nginx') {
            steps {
                script {
                    sh """
                        sshpass -p '${params.SSH_PASSWORD}' ssh -o StrictHostKeyChecking=no ${params.SSH_USER}@192.168.3.53 "rm -rf /home/sos/apps/koodo-reader/*"
                        sshpass -p '${params.SSH_PASSWORD}' scp -o StrictHostKeyChecking=no -r dist/* ${params.SSH_USER}@192.168.3.53:/home/sos/apps/koodo-reader/
                        sshpass -p '${params.SSH_PASSWORD}' ssh -o StrictHostKeyChecking=no ${params.SSH_USER}@192.168.3.53 "sudo systemctl reload nginx"
                    """
                }
            }
        }
    }
}